name: Code Coverage

on:
  push: 
  pull_request:
    branches: ["main"]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20', '1.21', '1.22' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
                
      - name: Lint
        run: golangci-lint run ./...

      - name: Format
        run: go fmt ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
