name: Release

on: 
    release: 
        types: [prereleased, published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.20

            - name: Build
              run: go build -v ./...

            - name: Test
              run: go test -v ./...

            - name: Release
              id: release
              run: |
                echo "Creating a release..."
                GOPROXY=proxy.golang.org go list -m github.com/patrickkabwe/go-validator@${{ github.event.release.tag_name }}
                echo "Release created!"

              